function battery_pack_thermal(varargin)
%BATTERY_PACK_THERMAL  Build + run a real Simscape Battery 100s2p thermal model.
%
%   battery_pack_thermal                      % build if needed, run, show viewer
%   battery_pack_thermal('Rebuild',true)      % force regeneration of the model
%   battery_pack_thermal('Run',false)         % build and open the model only
%   battery_pack_thermal('NPaPerMod',3,'NMod',3)   % small config, for a fast test
%
%   WHAT THIS BUILDS
%   ----------------
%   A genuine Simulink/Simscape model, battery_pack_100s2p.slx, containing
%   Simscape Battery module blocks generated by buildBattery from Battery
%   Builder objects and wired into a complete circuit:
%
%     * electrical : nMod modules in series, driven by a Controlled Current
%                    Source running a rest / CC-charge / rest / CC-discharge /
%                    rest duty cycle, with a Voltage Sensor across the pack.
%     * thermal    : every cell is an individual thermal node (Detailed model
%                    resolution).  Inside each module Simscape Battery builds
%                    cell-to-cell conduction AND radiation within each parallel
%                    assembly and between neighbouring parallel assemblies
%                    (orthogonal and diagonal pairs).  Each module exposes its
%                    two long faces as vectorised thermal nodes (XminH/XmaxH),
%                    and this script chains module k's XmaxH to module k+1's
%                    XminH.  That link is what closes the thermal network ACROSS
%                    module boundaries: the pack is one connected grid of
%                    coupled cell thermal nodes, 20 x 10 for the 100s2p default.
%     * cooling    : natural convection + radiation to still ambient air only.
%                    Every cell has its own thermal resistance to a single
%                    ambient node held at P.Tamb by a Temperature Source.
%                    That resistance is set per cell from how many neighbours
%                    shade it, so edge and corner cells run cooler than core
%                    cells.  There is no cooling plate and no coolant.
%
%   Files: this script, battery_pack_100s2p.slx, and a generated/ folder that
%   buildBattery fills with the Simscape component libraries the model links to.
%
%   Requires: Simulink, Simscape, Simscape Battery, Simscape Electrical.

%% ===================== 0. OPTIONS + PARAMETERS =====================
opt = struct('Rebuild', false, 'Run', true, 'NPaPerMod', 10, 'NMod', 10, ...
             'Open', true);
if mod(numel(varargin),2), error('Arguments must be name-value pairs.'); end
for i = 1:2:numel(varargin)
    f = char(varargin{i});
    if ~isfield(opt, f), error('Unknown option "%s".', f); end
    opt.(f) = varargin{i+1};
end

P = defaultParams(opt);

here   = fileparts(mfilename('fullpath'));
genDir = fullfile(here, 'generated');
mdl    = 'battery_pack_100s2p';     % must differ from this script's name
mdlF   = fullfile(here, [mdl '.slx']);

fprintf('=== %ds%dp 21700 pack: %d modules x %ds%dp = %d cells ===\n', ...
        P.Ns, P.Np, P.nMod, P.nPaPerMod, P.Np, P.N);
fprintf('    physical grid %d rows x %d cols\n\n', P.nRow, P.nCol);

%% ========================= 1. BUILD ===============================
if opt.Rebuild || ~isfile(mdlF)
    if opt.Rebuild
        if bdIsLoaded(mdl), close_system(mdl, 0); end
        if contains(path, genDir), rmpath(genDir); end
        if isfolder(genDir), rmdir(genDir, 's'); end
    end
    if ~isfolder(genDir), mkdir(genDir); end
    addpath(genDir);
    buildLibrary(P, genDir);
    buildModel(P, genDir, mdl, mdlF);
else
    addpath(genDir);
    fprintf('Using existing %s (pass ''Rebuild'',true to regenerate).\n\n', [mdl '.slx']);
end

if ~opt.Run
    if opt.Open, open_system(mdlF); end
    return
end

%% ========================== 2. RUN ================================
load_system(mdlF);
fprintf('Compiling and simulating (%d cells)...\n', P.N);
tSim = tic;
out  = sim(mdl, 'ReturnWorkspaceOutputs', 'on');
fprintf('  compile + solve: %.1f s wall clock\n', toc(tSim));

R = extractResults(out, P);
fprintf('  simulated %.0f s, %d samples on the viewer time base\n', R.t(end), numel(R.t));
fprintf('  Peak cell temperature   : %.1f degC\n', max(R.T(:)));
fprintf('  Peak spread across pack : %.1f K\n\n', max(max(R.T,[],1) - min(R.T,[],1)));

%% ========================= 3. VIEWER ==============================
showScrubber(R, P);

end % ======================= main =================================


%% ---------------------------------------------------------------
function P = defaultParams(opt)
%DEFAULTPARAMS  Everything tunable lives here.

P.Np        = 2;                 % cells per parallel assembly
P.nPaPerMod = opt.NPaPerMod;     % parallel assemblies per module
P.nMod      = opt.NMod;          % modules in the pack
P.Ns        = P.nPaPerMod * P.nMod;
P.N         = P.Ns * P.Np;

% Physical grid: each module is Np rows (the parallel group) x nPaPerMod cols,
% and modules stack in the row direction.  100s2p -> 20 x 10, the squarest
% arrangement available while every module stays a rectangle.
P.nRow = P.Np * P.nMod;
P.nCol = P.nPaPerMod;

% --- generic cylindrical 21700 NMC cell ---
P.D     = 21.55e-3;   % diameter                      [m]
P.H     = 70.15e-3;   % height                        [m]
P.mass  = 0.070;      % mass                          [kg]
P.cp    = 900;        % specific heat                 [J/kg/K]
P.Qnom  = 4.5;        % capacity                      [A*hr]
P.R25   = 0.022;      % DC resistance at 25 degC      [ohm]
P.kR    = -0.012;     % relative dR/dT                [1/K]

% --- packaging / heat transfer ---
P.pitch  = 23.0e-3;   % cell centre-to-centre spacing [m]
P.hConv  = 6.0;       % natural convection            [W/m^2/K]
P.emis   = 0.85;      % emissivity
P.Gcc    = 0.020;     % conduction, orthogonally adjacent cells  [W/K]
P.Gdiag  = 0.007;     % conduction, diagonally adjacent cells    [W/K]
P.shadow = 0.15;      % lateral area blocked per neighbouring cell
P.Arad   = 4.5e-4;    % radiation view area, orthogonal pairs    [m^2]
P.AradD  = 1.2e-4;    % radiation view area, diagonal pairs      [m^2]

% --- operating conditions ---
P.Tamb  = 25;         % ambient still air             [degC]
P.soc0  = 0.15;
P.Cchg  = 1.0;        % charge C-rate
P.Cdis  = 2.0;        % discharge C-rate
P.socHi = 0.95;
P.socLo = 0.10;
P.tRest0 = 60; P.tRestMid = 600; P.tRestEnd = 900;

% Three module variants are generated so that the two OUTER faces of the pack
% have no thermal node needing termination.  Foundation thermal blocks do not
% vectorise, so an exposed 1 x nCol face cannot be capped any other way.
P.libBase = 'batt21700';
if P.nMod == 1
    P.types = struct('name',{'ModuleSolo'}, 'xmin',{false}, 'xmax',{false});
elseif P.nMod == 2
    P.types = struct('name',{'ModuleTop','ModuleBot'}, ...
                     'xmin',{false,true}, 'xmax',{true,false});
else
    P.types = struct('name',{'ModuleTop','ModuleMid','ModuleBot'}, ...
                     'xmin',{false,true,true}, 'xmax',{true,true,false});
end
end


%% ---------------------------------------------------------------
function buildLibrary(P, genDir)
%BUILDLIBRARY  Battery Builder objects -> Simscape component libraries.

fprintf('Building Simscape Battery libraries...\n');

cm = batteryCellModelBlock;                     % Battery (Table-Based)
cm.BlockParameters.thermal_port = 'model';      % expose the cell thermal node
cm.BlockParameters.T_dependence = 'yes';        % temperature-dependent tables

geom  = batteryCylindricalGeometry(simscape.Value(P.H,'m'), ...
                                   simscape.Value(P.D/2,'m'));
cellO = batteryCell(geom, cm, ...
            Mass     = simscape.Value(P.mass,'kg'), ...
            Capacity = simscape.Value(P.Qnom,'A*hr'), ...
            Energy   = simscape.Value(P.Qnom*3.6,'W*hr'), ...
            Name     = "Cell21700");

mods = cell(1, numel(P.types));
for t = 1:numel(P.types)
    % Rows=Np makes the parallel group a COLUMN, so a module is a genuine
    % Np x nPaPerMod grid of cells rather than a 1-D strip.
    paO = batteryParallelAssembly(cellO, P.Np, Topology="Square", Rows=P.Np, ...
                                  ModelResolution="Detailed", Name="PA21700");
    paO.AmbientThermalPath            = 'CellBasedThermalResistance';
    paO.InterCellThermalPath          = 'on';
    paO.InterCellRadiativeThermalPath = 'on';

    modO = batteryModule(paO, P.nPaPerMod, ModelResolution="Detailed", ...
                         Name=P.types(t).name);
    modO.AmbientThermalPath            = 'CellBasedThermalResistance';
    modO.InterCellThermalPath          = 'on';   % cells inside a P-assembly
    modO.InterCellRadiativeThermalPath = 'on';
    if P.types(t).xmin, modO.XminThermalNodes = 'Vectorized'; end
    if P.types(t).xmax, modO.XmaxThermalNodes = 'Vectorized'; end
    mods{t} = modO;

    t0 = tic;
    buildBattery(modO, LibraryName=libOf(P,t), Directory=genDir, ...
                 MaskParameters="VariableNamesByType", ...
                 MaskInitialTargets="NumericValues", Verbose='off');
    fprintf('  %-11s built in %5.1f s\n', P.types(t).name, toc(t0));
    assert(isfile(fullfile(genDir,[libOf(P,t) '_lib.slx'])), ...
           'buildBattery did not produce %s_lib.slx', libOf(P,t));
end

% Topology of record: the equivalent Battery Builder pack object.
maO   = batteryModuleAssembly(mods{1}, CircuitConnection="Series", Name="ModuleAssembly");
packO = batteryPack(maO, Name="Pack");                               %#ok<NASGU>
m1 = mods{1};
fprintf('  cells per module %d, pack cells %d\n', m1.NumModels, P.N);
fprintf('  inter-cell connections per module        : %d\n', m1.NumInterCellThermalConnections);
fprintf('  inter-parallel-assembly conn. per module : %d\n\n', m1.NumInterParallelAssemblyThermalConnections);
end


%% ---------------------------------------------------------------
function s = libOf(P, t)
s = sprintf('%s_%s', P.libBase, lower(extractAfter(P.types(t).name, 'Module')));
end


%% ---------------------------------------------------------------
function ty = typeOfModule(P, k)
%TYPEOFMODULE  Which generated variant module k uses.
if numel(P.types) == 1
    ty = 1;
elseif k == 1
    ty = 1;
elseif k == P.nMod
    ty = numel(P.types);
else
    ty = 2;
end
end


%% ---------------------------------------------------------------
function pm = portMap(P, blk, ty)
%PORTMAP  Conserving-port indices for a generated module block.
%   Verified against the generated .ssc: left-side nodes come first in
%   declaration order (AmbH, then XminH), followed by the top node (+);
%   right-side nodes first (XmaxH), followed by the bottom node (-).

pm.amb = struct('side','LConn','i',1);
n = 1;
if P.types(ty).xmin
    n = n + 1;
    pm.xmin = struct('side','LConn','i',n);
end
pm.pos = struct('side','LConn','i',n+1);

m = 0;
if P.types(ty).xmax
    m = m + 1;
    pm.xmax = struct('side','RConn','i',m);
end
pm.neg = struct('side','RConn','i',m+1);

ph = get_param(blk,'PortHandles');
assert(numel(ph.LConn) == n+1 && numel(ph.RConn) == m+1, ...
   'Unexpected port count on %s: LConn=%d RConn=%d, expected %d and %d.', ...
   blk, numel(ph.LConn), numel(ph.RConn), n+1, m+1);
end


%% ---------------------------------------------------------------
function buildModel(P, genDir, mdl, mdlF)
%BUILDMODEL  Assemble the Simulink model around the generated module blocks.

fprintf('Assembling Simulink model...\n');
for t = 1:numel(P.types)
    load_system(fullfile(genDir,[libOf(P,t) '_lib.slx']));
end

if bdIsLoaded(mdl), close_system(mdl, 0); end
new_system(mdl); load_system(mdl);

x = 220; dy = 140;

% ---- modules -------------------------------------------------------
M = cell(1,P.nMod);  PM = cell(1,P.nMod);
for k = 1:P.nMod
    ty   = typeOfModule(P, k);
    src  = sprintf('%s_lib/%s', libOf(P,ty), P.types(ty).name);
    M{k} = sprintf('%s/Module%d', mdl, k);
    add_block(src, M{k}, 'Position', [x, 100+(k-1)*dy, x+100, 200+(k-1)*dy]);
    PM{k} = portMap(P, M{k}, ty);
end
pt = @(k,f) portOf(M{k}, PM{k}.(f).side, PM{k}.(f).i);

% ---- sources, references, sensors ---------------------------------
yBot = 100 + P.nMod*dy;
add_block('fl_lib/Electrical/Electrical Sources/Controlled Current Source', [mdl '/CCS'],  'Position',[60 100 100 160]);
add_block('fl_lib/Electrical/Electrical Elements/Electrical Reference',     [mdl '/EREF'], 'Position',[60 yBot 100 yBot+30]);
add_block('fl_lib/Electrical/Electrical Sensors/Voltage Sensor',            [mdl '/VS'],   'Position',[440 100 480 160]);
% Ambient air: a single-port absolute Temperature Source, so there is no
% reference-polarity ambiguity and no Simulink signal needed.
add_block('fl_lib/Thermal/Thermal Sources/Temperature Source',              [mdl '/AMB'],  'Position',[-90 300 -50 360]);
add_block('nesl_utility/Solver Configuration',                              [mdl '/SC'],   'Position',[-210 100 -170 130]);
add_block('nesl_utility/Simulink-PS Converter',                             [mdl '/I2PS'], 'Position',[-40 40 0 70]);
add_block('nesl_utility/PS-Simulink Converter',                             [mdl '/V2S'],  'Position',[540 110 580 140]);
add_block('simulink/Sources/From Workspace',                                [mdl '/Iref'], 'Position',[-180 35 -110 75]);
add_block('simulink/Sinks/To Workspace',                                    [mdl '/Vpack'],'Position',[620 110 680 140]);

set_param([mdl '/Iref'], 'VariableName','IpackTS', 'Interpolate','on', ...
          'OutputAfterFinalValue','Holding final value');
set_param([mdl '/AMB'], 'temperature', sprintf('%.4f', P.Tamb + 273.15), ...
          'temperature_unit', 'K');
set_param([mdl '/I2PS'], 'unit','A');
set_param([mdl '/V2S'],  'unit','V');
set_param([mdl '/Vpack'],'VariableName','Vpack','SaveFormat','StructureWithTime');

% ---- electrical: modules in series --------------------------------
% The source's "-" terminal feeds the pack "+", so a positive command drives
% current out of the pack, i.e. positive = discharge.
add_line(mdl, portOf([mdl '/CCS'],'RConn',2), pt(1,'pos'), 'autorouting','on');
for k = 1:P.nMod-1
    add_line(mdl, pt(k,'neg'), pt(k+1,'pos'), 'autorouting','on');
end
add_line(mdl, pt(P.nMod,'neg'), portOf([mdl '/EREF'],'LConn',1), 'autorouting','on');
add_line(mdl, portOf([mdl '/CCS'],'LConn',1), portOf([mdl '/EREF'],'LConn',1), 'autorouting','on');

% ---- thermal: chain the module faces ------------------------------
% This is what couples cells ACROSS module boundaries.  Module k's Xmax face
% carries one thermal node per parallel assembly; tying it to module k+1's
% Xmin face makes the whole pack a single connected grid of cell nodes.
for k = 1:P.nMod-1
    add_line(mdl, pt(k,'xmax'), pt(k+1,'xmin'), 'autorouting','on');
end

% ---- ambient node --------------------------------------------------
for k = 1:P.nMod
    add_line(mdl, portOf([mdl '/AMB'],'LConn',1), pt(k,'amb'), 'autorouting','on');
end

% ---- current command ----------------------------------------------
add_line(mdl, portOf([mdl '/Iref'],'Outport',1), portOf([mdl '/I2PS'],'Inport',1), 'autorouting','on');
add_line(mdl, portOf([mdl '/I2PS'],'RConn',1),   portOf([mdl '/CCS'],'RConn',1),   'autorouting','on');

% ---- voltage sensor + solver --------------------------------------
add_line(mdl, portOf([mdl '/VS'],'LConn',1), pt(1,'pos'), 'autorouting','on');
add_line(mdl, portOf([mdl '/VS'],'RConn',2), portOf([mdl '/EREF'],'LConn',1), 'autorouting','on');
add_line(mdl, portOf([mdl '/VS'],'RConn',1), portOf([mdl '/V2S'],'LConn',1), 'autorouting','on');
add_line(mdl, portOf([mdl '/V2S'],'Outport',1), portOf([mdl '/Vpack'],'Inport',1), 'autorouting','on');
add_line(mdl, portOf([mdl '/SC'],'RConn',1), portOf([mdl '/EREF'],'LConn',1), 'autorouting','on');

% ---- parameters ----------------------------------------------------
par     = cellParameters(P, genDir);
ambR    = ambientResistanceGrid(P);          % nRow x nCol, K/W
nPerMod = P.Np * P.nCol;
for k = 1:P.nMod
    rows = (k-1)*P.Np + (1:P.Np);            % this module's grid rows
    v    = zeros(1, nPerMod);
    for c = 1:P.nCol
        for lr = 1:P.Np
            v(P.Np*(c-1)+lr) = ambR(rows(lr), c);
        end
    end
    set_param(M{k}, 'AmbientResistance', mat2str(v, 6));
    % Initial targets are only honoured when their _specify flag is on;
    % otherwise the component's own default (SOC = 1) is used.
    set_param(M{k}, 'socCell_specify', 'on', 'socCell_priority', 'High', ...
              'socCell', sprintf('repmat(%.4f,%d,1)', P.soc0, nPerMod));
    set_param(M{k}, 'temperatureCell_specify', 'on', 'temperatureCell_priority', 'High', ...
              'temperatureCell', sprintf('repmat(%.4f,%d,1)', P.Tamb+273.15, nPerMod));
end

% ---- model workspace: parameter structs + current profile ---------
hws = get_param(mdl, 'ModelWorkspace');
f = fieldnames(par);
for i = 1:numel(f), assignin(hws, f{i}, par.(f{i})); end
[IpackTS, tEnd] = dutyCycle(P);
assignin(hws, 'IpackTS', IpackTS);

% ---- solver / logging ---------------------------------------------
set_param(mdl, 'Solver', 'daessc');
set_param(mdl, 'StopTime', sprintf('%.1f', tEnd));
set_param(mdl, 'RelTol', '1e-3');
set_param(mdl, 'AbsTol', '1e-4');
set_param(mdl, 'MaxStep', '5');
set_param(mdl, 'SimscapeLogType', 'all');
set_param(mdl, 'SimscapeLogName', 'simlog');
set_param(mdl, 'SimscapeLogDecimation', 1);
set_param(mdl, 'SaveOutput', 'on');
set_param(mdl, 'SaveFormat', 'Dataset');
set_param(mdl, 'PostLoadFcn', ...
    'addpath(fullfile(fileparts(which(bdroot)),''generated''));');

save_system(mdl, mdlF);
fprintf('  saved %s\n\n', [mdl '.slx']);
end


%% ---------------------------------------------------------------
function h = portOf(blk, side, idx)
ph = get_param(blk, 'PortHandles');
h  = ph.(side)(idx);
end


%% ---------------------------------------------------------------
function R = ambientResistanceGrid(P)
%AMBIENTRESISTANCEGRID  Per-cell resistance to ambient, from neighbour shading.
%   Both end caps of the cylinder are always exposed; each neighbouring cell
%   in the 4-neighbour grid blocks a share of the lateral area.  This is what
%   makes edge and corner cells run cooler than cells in the core.

A_lat = pi * P.D * P.H;
A_end = 2 * pi * P.D^2 / 4;
sigma = 5.670374e-8;
hRad  = 4 * P.emis * sigma * (P.Tamb + 273.15)^3;   % linearised radiation
hEff  = P.hConv + hRad;

r   = (1:P.nRow).';  c = 1:P.nCol;
nNb = (r > 1) + (r < P.nRow) + (c > 1) + (c < P.nCol);   % implicit expansion
A   = A_end + A_lat .* max(0.15, 1 - P.shadow*nNb);
R   = 1 ./ (hEff * A);
end


%% ---------------------------------------------------------------
function par = cellParameters(P, genDir)
%CELLPARAMETERS  Generated defaults, overridden with 21700 values.

% --- electrical: generic NMC 21700 ---
soc = [0 .05 .10 .20 .30 .40 .50 .60 .70 .80 .90 .95 1.00];
ocv = [3.00 3.35 3.45 3.55 3.62 3.68 3.75 3.83 3.93 4.02 4.12 4.17 4.20];
Tk  = [273.15 298.15 323.15];                    % 0 / 25 / 50 degC
V0  = ocv(:) + [-0.010 0 0.006];                 % mild temperature shift
shape = 1 + 0.35*exp(-soc(:)/0.08) + 0.12*exp((soc(:)-1)/0.06);
R0    = P.R25 * shape .* max(0.4, 1 + P.kR*(Tk - 298.15));

Cth   = P.mass * P.cp;                           % 63 J/K for a 21700
Rcc   = 1/P.Gcc;                                 % orthogonal neighbours
Rdiag = 1/P.Gdiag;                               % diagonal neighbours
sigma = 5.670374e-8;
nGap  = P.nPaPerMod - 1;

par = struct();
for t = 1:numel(P.types)
    % The generated .mat holds the Battery Builder OBJECT; the block parameter
    % values live in the generated _param.m script, so run that instead.
    S  = runParamScript(fullfile(genDir, [libOf(P,t) '_param.m']));
    fn = fieldnames(S);
    for i = 1:numel(fn)
        s = S.(fn{i});
        if ~isstruct(s), continue; end

        s.SOC_vecCell = soc;   s.T_vecCell = Tk;
        s.V0_matCell  = V0;    s.R0_matCell = R0;
        s.AHCell      = P.Qnom;
        s.V_rangeCell = [0 inf];
        s.thermal_massCell = Cth;

        % AmbientResistance is overridden per module block with a per-cell
        % vector; this value is only the fallback.
        s.AmbientResistance = 34;
        if isfield(s,'InterCellThermalResistance')
            s.InterCellThermalResistance = Rcc;      % the cells of one P-assy
        end
        if isfield(s,'XminThermalResistance')
            s.XminThermalResistance = Rcc/2;         % half the cross-gap path,
        end
        if isfield(s,'XmaxThermalResistance')
            s.XmaxThermalResistance = Rcc/2;         % so Xmax->Xmin sums to Rcc
        end
        % Between neighbouring parallel assemblies the mapping is, per gap,
        % (c1-c1)(c1-c2)(c2-c1)(c2-c2) -> orthogonal, diagonal, diagonal, orthogonal.
        if isfield(s,'InterParallelAssemblyThermalResistance') && nGap > 0
            s.InterParallelAssemblyThermalResistance = ...
                repmat([Rcc Rdiag Rdiag Rcc], 1, nGap);
        end

        % Radiation: Q = coefficient * area * (T1^4 - T2^4)
        if isfield(s,'InterCellRadiationCoefficient')
            s.InterCellRadiationCoefficient = P.emis * sigma;
            s.InterCellRadiationArea        = P.Arad;
        end
        if isfield(s,'InterParallelAssemblyRadiationCoefficient') && nGap > 0
            s.InterParallelAssemblyRadiationCoefficient = P.emis * sigma;
            s.InterParallelAssemblyRadiationArea = ...
                repmat([P.Arad P.AradD P.AradD P.Arad], 1, nGap);
        end

        par.(fn{i}) = s;
    end
end
end


%% ---------------------------------------------------------------
function S = runParamScript(f)
%RUNPARAMSCRIPT  Execute a generated _param.m and collect the structs it defines.
run(f);
clear f ans
vars = who;
S = struct();
for i = 1:numel(vars)
    v = eval(vars{i});
    if isstruct(v), S.(vars{i}) = v; end
end
end


%% ---------------------------------------------------------------
function [ts, tEnd, phases] = dutyCycle(P)
%DUTYCYCLE  Piecewise-constant pack current.  Positive = discharge.
%   Phase durations follow from coulomb counting, so the cycle needs no
%   feedback control and introduces no algebraic loop.

Ichg = P.Cchg * P.Qnom * P.Np;      % pack current during charge    [A]
Idis = P.Cdis * P.Qnom * P.Np;      % pack current during discharge [A]
tChg = (P.socHi - P.soc0) * 3600 / P.Cchg;
tDis = (P.socHi - P.socLo) * 3600 / P.Cdis;

phases = struct( ...
    'name', {'Rest','CC charge','Rest','CC discharge','Rest'}, ...
    'dur',  {P.tRest0, tChg, P.tRestMid, tDis, P.tRestEnd}, ...
    'I',    {0, -Ichg, 0, Idis, 0});

% Current changes over a short ramp rather than instantaneously.  An ideal
% current source stepping 18 A -> 0 in zero time is an algebraic discontinuity
% that makes the DAE solver stall; a 1 s ramp is both physically sensible and
% numerically clean, and costs ~0.5 A*s of throughput.
ramp = 1.0;
T = 0;  I = phases(1).I;  t = 0;
for k = 1:numel(phases)
    t = t + phases(k).dur;
    T(end+1) = t;         I(end+1) = phases(k).I;            %#ok<AGROW>
    if k < numel(phases)
        T(end+1) = t + ramp;  I(end+1) = phases(k+1).I;      %#ok<AGROW>
    end
end
tEnd = t;
ts   = timeseries(I(:), T(:));
end


%% ---------------------------------------------------------------
function R = extractResults(out, P)
%EXTRACTRESULTS  Pull per-cell temperature out of the Simscape log.

sl = out.simlog;
Tc = []; tv = [];
for k = 1:P.nMod
    node = sl.(sprintf('Module%d', k)).temperatureCell;
    v = node.series.values('K') - 273.15;        % [nT x cells in this module]
    if isempty(tv), tv = node.series.time; end
    Tc = [Tc, v]; %#ok<AGROW>
end

tg  = (0:10:tv(end)).';                          % uniform viewer time base
R.t = tg;
R.T = interp1(tv, Tc, tg).';                     % [nCells x nT]

% Module-local cell index -> pack grid.  Module layout is [1 3 5 ...;
% 2 4 6 ...], i.e. one column per parallel assembly.
idx = zeros(P.nRow, P.nCol);
for k = 1:P.nMod
    for c = 1:P.nCol
        for lr = 1:P.Np
            idx((k-1)*P.Np + lr, c) = (k-1)*P.Np*P.nCol + P.Np*(c-1) + lr;
        end
    end
end
R.gridIdx = idx;

try
    V = out.Vpack;  R.tV = V.time;  R.V = V.signals.values;
catch
    R.tV = tg;      R.V  = nan(size(tg));
end
[ts, ~, ph] = dutyCycle(P);
R.I = interp1(ts.Time, ts.Data, tg, 'linear', 'extrap');
R.phases = ph;
end


%% ---------------------------------------------------------------
function showScrubber(R, P)
%SHOWSCRUBBER  Top-down cell-temperature map with a time slider.

nRec = numel(R.t);
Tlo  = min(R.T(:));  Thi = max(R.T(:));
if Thi - Tlo < 1, Thi = Tlo + 1; end

fig = figure('Name', sprintf('Simscape %ds%dp 21700 pack', P.Ns, P.Np), ...
             'Color','w', 'Position',[60 60 1260 680]);

axG = axes('Parent',fig, 'Position',[0.05 0.20 0.40 0.66]);
im  = imagesc(axG, nan(P.nRow, P.nCol), [Tlo Thi]);
axis(axG,'image'); set(axG,'XTick',[],'YTick',[],'Box','on');
try
    colormap(axG, turbo);
catch
    colormap(axG, jet);
end
cbar = colorbar(axG); cbar.Label.String = 'Cell temperature [\circC]';
hold(axG,'on');
for k = 1:P.nMod-1                          % module boundaries
    y = k*P.Np + 0.5;
    plot(axG, [0.5 P.nCol+0.5], [y y], 'k-', 'LineWidth', 1.4);
end
ttl = title(axG, '', 'FontWeight','normal');

axT = axes('Parent',fig, 'Position',[0.56 0.58 0.39 0.33]);
tm = R.t/60;
hM = plot(axT, tm, max(R.T,[],1), 'r-','LineWidth',1.4); hold(axT,'on');
hA = plot(axT, tm, mean(R.T,1),   'k-','LineWidth',1.2);
hN = plot(axT, tm, min(R.T,[],1), 'b-','LineWidth',1.4);
yline(axT, P.Tamb, ':', 'ambient', 'HandleVisibility','off');
grid(axT,'on'); ylabel(axT,'T [\circC]');
legend(axT,[hM hA hN],{'max','mean','min'},'Location','northwest','Box','off');
title(axT,'Pack cell temperature (Simscape)','FontWeight','normal');
curT = xline(axT,0,'Color',[.3 .3 .3],'LineWidth',1.2,'HandleVisibility','off');

axI = axes('Parent',fig, 'Position',[0.56 0.20 0.39 0.28]);
yyaxis(axI,'left');  plot(axI, tm, R.I, 'LineWidth',1.4);
ylabel(axI,'I [A]  (+ = discharge)');
yyaxis(axI,'right'); plot(axI, R.tV/60, R.V, 'LineWidth',1.2);
ylabel(axI,'pack V');
grid(axI,'on'); xlabel(axI,'time [min]');
curI = xline(axI,0,'Color',[.3 .3 .3],'LineWidth',1.2);

sld = uicontrol(fig,'Style','slider','Units','normalized', ...
        'Position',[0.05 0.10 0.40 0.030],'Min',1,'Max',nRec,'Value',1, ...
        'SliderStep',[1/max(1,nRec-1) 20/max(1,nRec-1)]);
btn = uicontrol(fig,'Style','togglebutton','Units','normalized', ...
        'Position',[0.05 0.035 0.09 0.045],'String','Play','FontWeight','bold');
chk = uicontrol(fig,'Style','checkbox','Units','normalized', ...
        'Position',[0.16 0.040 0.29 0.035],'BackgroundColor','w', ...
        'String','Auto colour scale (per frame)', ...
        'Callback',@(~,~) draw(round(get(sld,'Value'))));
addlistener(sld,'ContinuousValueChange',@(s,~) draw(round(get(s,'Value'))));
set(sld,'Callback',@(s,~) draw(round(get(s,'Value'))));
set(btn,'Callback',@playCB);
draw(1);

    function draw(k)
        k  = max(1, min(nRec, k));
        Tk = reshape(R.T(R.gridIdx, k), P.nRow, P.nCol);
        set(im,'CData',Tk);
        if get(chk,'Value')
            lo = min(Tk(:)); hi = max(Tk(:));
            if hi-lo < 0.05, hi = lo+0.05; end
            set(axG,'CLim',[lo hi]);
        else
            set(axG,'CLim',[Tlo Thi]);
        end
        set(curT,'Value',R.t(k)/60); set(curI,'Value',R.t(k)/60);
        set(ttl,'String',{ ...
            sprintf('t = %.1f min   |   %s', R.t(k)/60, phaseAt(R.t(k), R.phases)), ...
            sprintf('T  min %.1f / mean %.1f / max %.1f \\circC', ...
                    min(Tk(:)), mean(Tk(:)), max(Tk(:)))});
        drawnow limitrate;
    end

    function playCB(src,~)
        if get(src,'Value')==1
            set(src,'String','Pause');
            k = round(get(sld,'Value'));
            while isvalid(src) && get(src,'Value')==1 && isvalid(fig)
                k = k+1; if k>nRec, k=1; end
                set(sld,'Value',k); draw(k); pause(0.02);
            end
            if isvalid(src), set(src,'String','Play'); end
        else
            set(src,'String','Play');
        end
    end
end


%% ---------------------------------------------------------------
function s = phaseAt(t, phases)
acc = 0; s = phases(end).name;
for k = 1:numel(phases)
    acc = acc + phases(k).dur;
    if t <= acc, s = phases(k).name; return; end
end
end
